hosts:
- hostName: buckwasher
  ipAddress: "192.168.14.34"
  OS: "linux"
  classpath: "/home/mtiddens/tools.jar"
- hostName: mtserver
  ipAddress: "192.168.14.12"
  OS: "linux"
  classpath: "/home/mtiddens/tools.jar"
- hostName: local
  ipAddress: "127.0.0.1"
  OS: "windows"
  classpath: "C:\\mydir\\gitrepos\\Aeron\\aeron-tools\\build\\libs\\tools.jar"
  javaPath: "C:\\mydir\\Java\\jdk1.8.0_40\\bin"
  tmpDir: "C:\\tmp"